#|
#|    bypass all "anticraftitem.bypass"
#|    bypass one item "anticraftitem.ITEM"
#|
bypass-permission: "anticraftitem"
no-permission-message:
  - '&cYou do not have permission..'

#| blocked-items list
blocked-items:
  #| "ITEM"
  - "WOOD_DOOR"
